---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-books
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-bookdrop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
