---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theforest-saves
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi

