---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fusion-secret
  namespace: apps
spec:
  encryptedData:
    fusion-password: AgC24JP9hLGfWQ92EPcVSC4wVjT+aJWCOVX/rk3cPvqQvccyAIJA1UJESPoG4hFsyBJgqG2f2AlBS3IZdeRwLOazDr4kFCTOxKT7gwlG+f4O+92COGp0EIby7R14lkf8pmRcfLZzieYDlhGEvW3InHZqfpJyvif7UU0sbU44xz/91tuZU1Q6L5Ue7jCVPXOXGaN+/Ae4P6vXvC/Vkje2Y+bwmdD1AgBhx14owdZQiWZ/JUwS/m0sf0oQ74sYRUZpDhvuDyaFSmmjBXT1RgYAwDSTFUjDEkv1+hxKps6+sIqtSE9hnvPwO+GTNZ0SPcltu8D4EAjLtFCUy/fwZA0F0LqwETE9v+Ejk36WYMC+iM51mkZdJaz7k1hR4d1Ce4zAvBsIJSln006A4Ig/Eh8YrRgo69IdsfolJR5KbrNtwWJdUyj+qcTbNcwLUxMYkgaVZPuUDcHh4z1j+O3KbwC9PhMJFSGf6dzmTWMrZvhmNi+HpSp3l+6NkJEYfmicO8oTPMNnlcXz3/ESDF7fbyHrbPZxJELbFhh7hYLpKANZcnpabFMpHxPC64Nh5RbhbmrUokzcefnWYmeBKCtmlpDixJhCnX4kPxMLYeWbhbi0wBnf4AInqyBJxTxsfsGjvnPi9NTBljFBfvTxZ4fpxVbK3Vn+ZT009Z7NM99AEZeunxG6+B3zQEgjNoIkslyB2i+EEIJrTQVzjukr3XrSMOWKGNInUw9Igv1LwH2mV8TW6LgusUs=
  template:
    metadata:
      name: fusion-secret
      namespace: apps
