---
helmDefaults:
  kubeContext: homelab

hooks:
  - events: ["prepare"]
    showlogs: true
    command: "kubectl"
    args:
      - "config"
      - "set-context"
      - "--current"
      - "--namespace=kube-system"

repositories:
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: traefik
    url: https://traefik.github.io/charts
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: jetstack
    url: https://charts.jetstack.io
  - name: jellyfin
    url: https://jellyfin.github.io/jellyfin-helm
  - name: ghcr
    url: ghcr.io
    oci: true

releases:
  ## system
  - name: metallb
    namespace: kube-system
    chart: metallb/metallb
  - name: metallb-config
    namespace: kube-system
    chart: charts/metallb
    needs:
      - metallb
  - name: traefik-crds
    chart: traefik/traefik-crds
    values:
      - gatewayAPI: true
  - name: traefik 
    namespace: kube-ingress
    createNamespace: true
    chart: traefik/traefik
    values:
      - globalArguments: []
      - providers:
          kubernetesCRD:
            allowExternalNameServices: true
            enabled: true
          kubernetesIngress:
            allowExternalNameServices: true
            enabled: true
          kubernetesGateway:
            enabled: true
      - service:
          annotations:
            service.beta.kubernetes.io/metal-lb: "true"
            metallb.universe.tf/address-pool: default-pool
      - logs:
          general:
            level: "DEBUG"
  - name: sealed-secrets
    namespace: kube-system
    chart: sealed-secrets/sealed-secrets
    set:
      - name: fullnameOverride
        value: sealed-secrets-controller

  ## storage
  - name: local-path-provisioner-namespace
    chart: charts/local-path-provisioner-namespace
  - name: local-path-provisioner
    namespace: kube-storage
    chart: charts/local-path-provisioner
    values:
      - nodePathMap:
        - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
          paths:
            - /var/local-path-provisioner
      - storageClass:
          defaultClass: true
  - name: nfs-external-provisioner
    namespace: kube-storage
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    values:
      - nfs:
          server: 10.0.0.200
          path: /volume1/homelab

  ## certificates
  - name: cert-manager
    namespace: kube-certs
    createNamespace: true
    chart: jetstack/cert-manager
    set:
      - name: crds.enabled
        value: true
  - name: cert-manager-config
    namespace: kube-certs
    chart: charts/cert-manager
    needs:
      - cert-manager

  ## external
  - name: unifi
    namespace: kube-ingress
    chart: charts/unifi
  - name: synology
    namespace: kube-ingress
    chart: charts/synology

  ## apps
  - name: kavorites
    namespace: kavorites
    createNamespace: true
    chart: charts/kavorites
  - name: homebridge-namespace
    chart: charts/homebridge-namespace
  - name: homebridge
    namespace: homebridge
    chart: charts/homebridge
  - name: pinchflat
    namespace: pinchflat
    createNamespace: true
    chart: charts/pinchflat
  - name: freshrss
    namespace: freshrss
    createNamespace: true
    chart: charts/freshrss
  - name: jellyfin
    namespace: jellyfin
    chart: jellyfin/jellyfin
    values:
      - ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            kavorites.koudijs.app/title: Jellyfin
            kavorites.koudijs.app/image-url: https://avatars.githubusercontent.com/u/45698031
          hosts:
            - host: media.koudijs.me
              paths:
                - path: /
                  pathType: ImplementationSpecific

          tls:
            - secretName: jellyfin-cert
              hosts:
                - media.koudijs.me
      - persistence:
          media:
            accessMode: ReadWriteMany
            size: 25Gi
            storageClass: nfs-client
  - name: adguard-namespace
    chart: charts/adguard-namespace
  - name: adguard
    namespace: adguard
    chart: charts/adguard
  - name: invoiceshelf
    namespace: invoiceshelf
    chart: charts/invoiceshelf
  - name: worldle-bot
    namespace: worldle
    createNamespace: true
    chart: charts/worldle-bot

  - name: github-actions-controller
    namespace: github-actions
    createNamespace: true
    chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    version: 0.12.1

  - name: github-actions-secrets
    namespace: github-actions
    chart: charts/github-actions-secrets

  - name: github-actions-lanlords
    namespace: github-actions
    chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    version: 0.12.1
    values:
      - githubConfigUrl: "https://github.com/lanlords"
      - githubConfigSecret: github-actions-lanlords
      - controllerServiceAccount:
          name: github-actions-controller-gha-rs-controller
          namespace: github-actions