---
version: "3"

dotenv:
  - .env

includes:
  helm:
    taskfile: ./helm/taskfile.yaml
    dir: ./helm
  talos:
    taskfile: ./talos/taskfile.yaml
    dir: ./talos

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
