apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-issuer
spec:
  # The CA URL:
  url: https://step-certificates.kube-system.svc.cluster.local
  # The base64 encoded version of the CA root certificate in PEM format:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3akNDQVdtZ0F3SUJBZ0lRT2l3aGxYekJFbm5XcXRCVEoyeFVTekFLQmdncWhrak9QUVFEQWpCQU1Sb3cKR0FZRFZRUUtFeEZUZEdWd0lFTmxjblJwWm1sallYUmxjekVpTUNBR0ExVUVBeE1aVTNSbGNDQkRaWEowYVdacApZMkYwWlhNZ1VtOXZkQ0JEUVRBZUZ3MHlOakEzTWpreU1EUXhNVGRhRncwek5qQTNNall5TURReE1UZGFNRUF4CkdqQVlCZ05WQkFvVEVWTjBaWEFnUTJWeWRHbG1hV05oZEdWek1TSXdJQVlEVlFRREV4bFRkR1Z3SUVObGNuUnAKWm1sallYUmxjeUJTYjI5MElFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUU0UjZ3WmIxNwo0VU1SbFMzSS85M052cHUxcVlZaXNLMlBHU0tOQU0vZUo3YTNtcSt5M3NaT1NWdmlkMm0yenk1d0I4ZXBCUENFCkd5bzNSeUhLeGxNS09hTkZNRU13RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOEMKQVFFd0hRWURWUjBPQkJZRUZQVzVMMXZUK3JSOTlYTkYvMVczWVp0K01qNThNQW9HQ0NxR1NNNDlCQU1DQTBjQQpNRVFDSUJlNkg2MFlvS1dHUDlHQlZEdUNUK0N2d2wyOWVwMUd6K3ZxY3RXcDVyUElBaUJvcFEwNTloSVJyV3NiCkgrWWZuNDQzVERUMDZFa3JYMEt6cFM4a2FaWjNjdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  # The provisioner name, kid, and a reference to the provisioner password secret:
  provisioner:
    name: admin
    kid: ZUJ4Fe6aDvLJ9rHaxOXe-B9fKD0LhfPIAzcxKTr84Dw
    passwordRef:
      name: step-certificates-provisioner-password
      key: password
      namespace: kube-system
