---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
        - name: samba
          image: dockurr/samba:latest
          env:
            # - name: UID
            #   value: "1002"
            # - name: GID
            #   value: "1005"
            - name: NAME
              value: Data
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: samba-secret
                  key: USER
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: samba-secret
                  key: PASS
          ports:
            - name: smb
              containerPort: 445
              protocol: TCP
          volumeMounts:
            - name: navidrome-music
              mountPath: /storage/navidrome-music
      volumes:
        - name: navidrome-music
          persistentVolumeClaim:
            claimName: navidrome-music
