---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-secret
  namespace: apps
spec:
  encryptedData:
    PASS: AgBgeo9dgctsOpReGS3Yvk/qugSCDWcvaoZbJ7TmKbBR0aHaexcmXSeFyFNaXT6HEQFRqwubXTPJd9/odZHDm1UGBcFOKBnIZsnrMSpBzGqjiZAf1E/YLTqIj4BKbJKZeP/4PHbAzJU8X1Hv9Wx2UHCZts+1zJFI9srRsIwUEwx6sggY/0aBTktQG6ocRKJgE+YXnwdVCeJXVsYoGztcFEa4WCNxIlXHY+/1wXnyJGfzhEE0/Oo1N/yjXilHPXCf76izVWZ3HANx2yEzmt73PmMosvCQHLCSeGJ2CcWu4cOr3VWdRsumCB0ewQLmL2MrxEeARRpzZJFq4H0gK1NBYjo0m7aqf6tw0jtLgopuPRpKUGat0aGDpQN8B5vP7himXGNszLd87UgjUPlAr6LHGZlNqAotnNtbi3EN5/4dAHAxvGrQdF2o4+vla08NKDY0dNTBkDCw0GByw74K63jpGNSfHXsya71qW/X/GpS+6o7rjh698Gdwlo7IZ0hmkynZQZGrN3+w00NaAVnq+eJpr1EEm+Xp9ys4xXZkLKaDiapTMWr+RM4aO5M4opxk3EOVbWLmRLkYCUEbSKl2N084Dmdch2tC3dMq7aWtBRVTdnlmIiYhqGFw7k48EYJYFEkXaJtm4iG/gx+7tGwGqlHejM6vEbm4azo4DUwr5jUd0uSXHLOk4oSbzg968/IowDiHeRXcSnPNKkDlxS1pX8CW/cBdAmWOCg==
    USER: AgBR+UjarSETfT3cXVPL/iVm5VHWELc4VGttlLqYf5lrQIu9i0lgdfx8TFM9PUZVrtsEsns4uTzwmCqB6t3jOaylKF0MBkDjnjP3IjZRATfsITye64bMCWmT6PDOl1rgXpfdxpGmY/zomQrsPbkeZ+VtesqvNTG+Fs6uaLKuccuOBSimbRmb1kWP5hwFJtQg3BglMbWeKYvxvr0Js8ARvqPxsE/V6Qiv7BckcwTO7A6Otg95Y549HGu7AdH1wbrDlH0kKIH8+wLWXMzWaj+prBH3ITXum9SK8/PnHjGoEkAIg+3B1hwCd6zbqW/XIUQErJLmdAGQIzygH6DGyCuWAnTpDNBMMh+c1M4wNe9KRfjcDosG+vgQe8i4vGGleWRxSwQ0hWeZ2wIfjYDAXDG505IVSVnSxiyAy7uVaLDFOvbIpeeh2ohgBh7myEiLSiRnvQ0010FLsG9/KEgMG+0+idreKadKdUAmOWvXrfQQocJztg4vwDOANZIFC7SnUC+bKDX41GqF60A1Ikz2RMHQ1GCkRuMF+cQPfKskHvhSWukB2PL7KSiNXBwRst+PyKy9WtsXRtj+fDDUpOqTmKfkjHbkqIAKBsL2WooWRqHtpJ3ufUsSzlpBbnQkwAbRO35sURXhhN+blpaF27rkdXFrlnsTqP03oTAL6aGfVblOAqk1VmpdOkrDp/HESRqORRqGg53eI8L8
  template:
    metadata:
      name: samba-secret
      namespace: apps
    type: Opaque
