---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: synology-cert
spec:
  secretName: synology-tls
  dnsNames:
    - nas.koudijs.me
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
