---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: homebridge
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - host: bridge.koudijs.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  homebridge
                port:
                  number: 8581
  tls:
    - secretName: homebridge-cert
      hosts:
        - bridge.koudijs.me
