---
apiVersion: v1
kind: Service
metadata:
  name: docmost-redis
  labels:
    app: docmost-redis
spec:
  ports:
  - port: 6379
    name: redis-tcp
  clusterIP: None
  selector:
    app: docmost-redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docmost-redis
spec:
  selector:
    matchLabels:
      app: docmost-redis
  serviceName: docmost-redis
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: docmost-redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis-tcp
