---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmost-cloudflared
spec:
  selector:
    matchLabels:
      app: docmost-cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: docmost-cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.11.1
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: cloudflare-tunnel-docmost
        - name: config
          configMap:
            name: docmost-cloudflared-config
            items:
              - key: config.yaml
                path: config.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docmost-cloudflared-config
data:
  config.yaml: |
    tunnel: docmost-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: wiki.jona.io
        service: http://docmost-app:3000
      - service: http_status:404
