apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavorites
  labels:
    app: kavorites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavorites
  template:
    metadata:
      labels:
        app: kavorites
    spec:
      serviceAccountName: kavorites
      containers:
        - name: kavorites
          image: jonakoudijs/kavorites:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
            - name: HOST
              value: "0.0.0.0"
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kavorites
  labels:
    app: kavorites
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: kavorites
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kavorites
  labels:
    app: kavorites
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kavorites
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kavorites
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kavorites
subjects:
- kind: ServiceAccount
  name: kavorites
  namespace: default 