---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  labels:
    app: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      hostNetwork: true
      containers:
        - name: adguard-home
          image: adguard/adguardhome:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 67
              protocol: UDP
            - containerPort: 68
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 443
              protocol: UDP
            - containerPort: 853
              protocol: TCP
            - containerPort: 853
              protocol: UDP
            - containerPort: 3000
              protocol: TCP
            - containerPort: 5443
              protocol: TCP
            - containerPort: 5443
              protocol: UDP
            - containerPort: 6060
              protocol: TCP
          volumeMounts:
            - mountPath: "/opt/adguardhome/conf"
              name: adguard-conf
            - mountPath: "/opt/adguardhome/work"
              name: adguard-work
      volumes:
        - name: adguard-conf
          persistentVolumeClaim:
            claimName: adguard-conf
        - name: adguard-work
          persistentVolumeClaim:
            claimName: adguard-work
