---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: adguard-home
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - host: guard.koudijs.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  adguard-home
                port:
                  number: 8581
  tls:
    - secretName: adguard-home-cert
      hosts:
        - guard.koudijs.me
