---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
