---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-redis-credentials
  namespace: apps
spec:
  encryptedData:
    password: AgAEfHvwn/eLC2P33diir2N3pFMZJIeDbGPDbUDDfZ7D6ZNKMtdaG9B9YHvBiCPa3dS/6aoUnLU4cAs55xE2Jyiw7AvNW7VgunRh4Oh7QYW2VVixH8zhHLP4JmnUjh7aroTA+lxCLnWsR1q7x6r3aVD1kfPzEl4kv1zz+HoqePQ9JRHO1foMFzbyksk+RvbHukgY8b5yNkbq9FV0yaARSHFIpe6i4QRnAs5eHyaFJVDlGOb5+VlqBuOkD1Zft0TXhK0KWpQKNuMHtrQy47+LDCrTSEppN9jKWt1NO/0STAraWZQHaOihO3tegHZQpmgWL6DwbV7+5RrAIBL5NfzqbsKVBVZUQVH5q3Ycrbql4EW9PAQb88dseQ61Hd71uW2VAfGsQwSkzEdliklWq/B+j/pwZ6SM+npwsTxs0eoOyJqbVUxQQ/KsnjyJ7EZqfA9seRMSOgNGZYe1ydFhzSIycnyFUBBUxhg3gx7SxRSvnwqeDnZ4dQFX60WQnN608UFDWvJkMCF3WetFW7LMAe9GHwjSGJGk4o3EIaeMQKxQ6bmWi/y5MpGG5bGuqyknHcsGrKtcwT5g+BIYWwMOQ8xeEAZRd5yrAWSITC3eY4DkKz+lNXlilDbcy4V53UGzEePENMvukB+3qnPtF0H/PduGNw5EQtxNyoufHJmrIlktcZFKO8Ewi7qcQAoysvIQNqvHGQM7xshNsNDiMvf3qVEdT80J8KIVvA==
  template:
    metadata:
      name: nextcloud-redis-credentials
      namespace: apps
