---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-secret
  namespace: apps
spec:
  encryptedData:
    nextauth-secret: AgAqxTUoPBJ8g10KtcA973wdClxWDIH6ew+dF2AcWosiutk59miajWRcJHA86s4E5Vfd+YWL7WhGlEkc201Ju7AnI2ttQsqMlssJIJvGpTRGWV5ZVX0IsJqze6d9w/WOS9v+hq3pdAt9OZ94ZOcwiWxJ8SJ0PAuMwMk7/j5l2lSQgYy3uNA9NVAf5QNKxmqC1XweQuMLt685jlnbMQaa7Wqbz4aSqihsEUmR9PJpLe/Uou/pyUCbUYcO5Pn9SIL8Bh1nXTjxtt2eXdJ37CFnwytaW5Rjz30WTH4cy69lsKHz3zvya1Zb2TrBxAPVwF+PGuFQTWvt7CQPjoN+F5mPXpiehKxKhEN9Jae4X6i5ZmU4jl7LxYCsVMcd+X1RduXuOj/5/buHmphf0wO3uQUNp/FzuRB/n/OksBEXEZFUHRJCmDBAQEQQ5KCrIL5/e1Y2SeKQwvkOfzkdEjkMldbVYRRdQ3it/bS3l4JEeCwKKAzaZsmsM4yg1KiPDsP/xb3wshBk6L5v5C5a3CgKFWSCGHX5oXVGDMMGD/4f6b7cngFchTsERorMkZK4bbBUj4NpJROLZpS5pknV0VvPo+d7gXyxFGez5sjkc/L0scbm4edULXeQF49h9AzsViKz/Yju+T94SSAKxdzTBjP21ox879NwTpdCv6u2e6fZRfMVClxPDVGbZ5AQKhljl+oedZ680u2CXNKvo7ijn5epjPyfDL4h9RT8h2GxUxqx1ZOGB+V+d7mSIcFDUFKFmhLorJzi+Ligy9mniBMNeqFXIkh9JSI0
  template:
    metadata:
      name: karakeep-secret
      namespace: apps
