---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cloud-key-cert
spec:
  secretName: unifi-cloud-key-tls
  dnsNames:
    - unifi.koudijs.me
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
