---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: kube-certs
spec:
  encryptedData:
    api-token: AgBw8jdgYVnIchbNUQzJCDAX4LeDEYmcydZXLaJAAFjNyxOaS2zJ5M1xY/UtpAcwtTPyZLmakyLRmN+g78cA5ngAuV1MurYgCIQqQNptVQa9WD7zqBETUJV1zsf2NjXySfiDkLdwdtc+I9107g8DqAmYAfx4Seg2i+8fIMeWMfROFzlE74tl82Biq7mevRIjHC0Dj2KSMT4rcv2lioIUQZ0sh4cL2rGfI/5D0NylsSo9xxEKvxGZnBWy8eq+q3/lx3StCDFlrkMFDFwt39y7sH+j2LOjrSghLzhTSc7A+cvJrevh3Z8Ri5osl01BwpSl46YrCOmxO2DKlcbHKb8YdjTwYG+HR1UVU3EweAuSVE4J3swj49bmRPHznPfVxe7Yse1uiVoohpU1A/r4RE55jVmKjKxbAOkMtf/UbDO3+3b99YM/jhWPjG3a0zryhu7zqidbzz9O3Iq2+CVJ36ksmVYnaEgQNqQH8i+LRWiIemjzaa7llBJbcnMnz/zY3QTLm4l49jxiiRYhQaL85ZnXH4tVhQ6TYsQcEn+d0nDfbF+ryhuD1zlistGvSQOlEbc5bge/YS4noC6786H4wkOoznXzGT4WVksmYfyRlJG9VtfPc/8UtYG50hdp4iBrPb6eAFp2N7U2JjpFCMiDVhWropQUQggFhTcp4zLlO1mMH561OGkpIUAGXLY9P8PkM4mv86m+3TU7l2jJP/sNP4izIzNvmctUKxEz3ZGV/YikzQ7znv8iyhV5mmdF
