---
helmDefaults:
  kubeContext: homelab

hooks:
  - events: ["prepare"]
    showlogs: true
    command: "kubectl"
    args:
      - "config"
      - "set-context"
      - "--current"
      - "--namespace=kube-system"

releases:
  ## apps
  - name: apps-namespace
    chart: charts/apps-namespace
  - name: unifi
    chart: charts/unifi
    namespace: apps
  - name: fusion-rss
    chart: charts/fusion
    namespace: apps
  - name: monochrome
    chart: charts/monochrome
    namespace: apps
  - name: karakeep
    chart: charts/karakeep
    namespace: apps
  - name: navidrome
    chart: charts/navidrome
    namespace: apps
  - name: jellyfin
    chart: jellyfin/jellyfin
    namespace: apps
    values:
      - persistence:
          config:
            enabled: true
            size: 5Gi
          media:
            enabled: true
            size: 50Gi
            accessMode: ReadWriteMany
      - ingress:
          enabled: true
          hosts:
            - host: media.koudijs.lan
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: media-koudijs-lan
              hosts:
                - media.koudijs.lan
  - name: jellyfin-config
    chart: config/jellyfin
    namespace: apps
  - name: nextcloud-config
    chart: config/nextcloud
    namespace: apps
  - name: nextcloud
    chart: nextcloud/nextcloud
    namespace: apps
    values:
      - nextcloud:
          host: cloud.koudijs.lan
          extraEnv:
            - name: OVERWRITEPROTOCOL
              value: "https"
            - name: TRUSTED_PROXIES
              value: "10.244.1.0"
            - name: OVERWRITECONDADDR
              value: "^10\\.244\\.1\\.0$"
      - ingress:
          enabled: true
          tls:
            - secretName: cloud-koudijs-lan
              hosts:
                - cloud.koudijs.lan
      - service:
          annotations:
            traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
      - internalDatabase:
          enabled: false
      - externalDatabase:
          enabled: true
          type: postgresql
          #host: "myhost:1234"
          existingSecret:
            enabled: true
            secretName: nextcloud-db-credentials
            usernameKey: username
            passwordKey: password
            databaseKey: database
            hostKey: host
      - redis:
          enabled: true
          auth:
            enabled: true
            existingSecret: nextcloud-redis-credentials
            existingSecretPasswordKey: password
          global:
            storageClass: longhorn-single-replica
      - persistence:
          enabled: true
      - cronjob:
          enabled: true

  ## cnpg
  - name: cnpg-config-apps
    chart: config/cnpg-apps
    namespace: apps

  ## system
  - name: metallb-config
    namespace: kube-system
    chart: config/metallb
  - name: longhorn-config
    namespace: kube-system
    chart: config/longhorn
  - name: keel
    namespace: kube-system
    chart: keel/keel
    values:
      - service:
          enabled: true
          type: ClusterIP
          externalPort: 9300
          #clusterIP: ""
      - basicauth:
          enabled: true
          user: "jona"
          password: "sahnop-6boqna-joQtik"
      - ingress:
          enabled: true
          hosts:
            - host: keel.koudijs.lan
              paths:
                - /
          tls:
            - secretName: keel-koudijs-lan
              hosts:
                - keel.koudijs.lan
  - name: keel-config
    namespace: kube-system
    chart: config/keel
  - name: samba-server
    namespace: apps
    chart: charts/samba

  ## ingress
  - name: traefik
    namespace: kube-system
    chart: traefik/traefik
    values:
      - ingressClass:
          enabled: true
      - api:
          dashboard: false
      - providers:
          kubernetesCRD:
            allowCrossNamespace: true
            allowExternalNameServices: true
          kubernetesIngress:
            allowExternalNameServices: true
            enabled: true
          kubernetesGateway:
            enabled: true
      - gateway:
          listeners:
            web:
              namespacePolicy:
                from: All
      - service:
          annotations:
            service.beta.kubernetes.io/metal-lb: "true"
            metallb.universe.tf/address-pool: default-pool

  ## certificates
  - name: issuers
    namespace: kube-system
    chart: config/issuers
